## Linear Algebra Quiz #2

![title](./img/2_1.jpeg)

We strongly suggest working with numpy :)

In [1]:
import numpy as np
import sympy as sy

![title](./img/2_2.png)
- Which vectors below define a plane spanned by a linear combination?

In [63]:
def plane(a,b,c):
    #returns false if the vectors don't define a plane and returns which are those vectors if true
    mat = np.array([a,b,c])
    _, inds = sy.Matrix(mat).rref()
    return False if  len(inds) < 2 else mat[inds,:]

# Harder exercise

def complete_plane(*inputs):
    #returns the first set of vectors to complete a plane, false otherwise
    mat = np.array(inputs)
    _, inds = sy.Matrix(mat).rref()
    return False if  len(inds) < 2 else mat[inds,:]

In [64]:
v1=[1,2,3]
v2=[2,2,2]
v3=[8,8,8]
v4=[1,1,1]
print(plane(v1,v2,v3))
print(plane(v4,v2,v3))
print(complete_plane(v4,v1,v2,v3))

[[1 2 3]
 [2 2 2]]
False
[[1 1 1]
 [1 2 3]]


![title](./img/2_3.png)
- What is the solution for a and b?

In [56]:
def linearly_dependent(arg):
    mat = np.array(arg)
    _, inds = sy.Matrix(mat).rref()
    
    return len(inds) != mat.shape[0]
    
def solve_linequa(A,b):
    if linearly_dependent(np.c_[ A, b]):
        return "infinitly many solutions"
    elif linearly_dependent(A):
        return "no solution"
    else:
        return np.linalg.inv(A).dot(b)

In [58]:
A = np.array([[2, 3], [10, 15]])
b = np.array([[-1],[-5]])
print(solve_linequa(A,b))


infinitly many solutions


![title](./img/2_4.png)
- What is the solution for a and b?

In [59]:
A = np.array([[-1, 3], [-1, 3]])
b = np.array([[1],[5]])
print(solve_linequa(A,b))

no solution


In [65]:
#personal test for problem with solution
A = np.array([[-3, 3], [-1, 3]])
b = np.array([[1],[5]])
print(solve_linequa(A,b))

[[2.        ]
 [2.33333333]]
