## Linear Algebra Quiz #3

![title](./img/3_0.jpeg)

We strongly suggest working with numpy :)

In [1]:
import numpy as np
import copy as cp

![title](./img/3_2.png)
![title](./img/3_3.png)
Create a program that can output

- What is the value of element c23​ of Matrix C where C=A x B ?
- What is the value of element c23​ of Matrix C where C=B x A ?

In [2]:
def get_c_ij(A,B,i,j):
    C = np.matmul(A,B)
    return C[i-1,j-1]

A = [[3,1,2],[-5,4,1],[0,3,-8]]
B = [[0,5,-1],[3,2,-1],[10,0.5,4]]
i,j=2,3
sol1 = get_c_ij(A,B,2,3)
sol2 = get_c_ij(B,A,2,3)

print("Value of c"+str(i)+""+str(j)+" for matrix C=AxB: "+str(sol1))
print("Value of c"+str(i)+""+str(j)+" for matrix C=BxA: "+str(sol2))

Value of c23 for matrix C=AxB: 5.0
Value of c23 for matrix C=BxA: 16.0


In [3]:
# okay numpy is great but... how would you inverse a matrix by hand?

def inverse_matrix(A):
    return np.linalg.inv(A)

print(inverse_matrix(A))

[[ 0.2        -0.08        0.04      ]
 [ 0.22857143  0.13714286  0.07428571]
 [ 0.08571429  0.05142857 -0.09714286]]


![title](./img/3_1.png)
Create a program that can output

- What is the value of the ijth element if i = 2 and j=3?
- What is the value of the ijth element if i = 3 and j=1?

In [4]:
def get_d_ij(A,B,C,i,j):
    C = np.array(A) + np.array(B) - np.array(C)
    return C[i-1,j-1]

A = [[3,0.6,4,-3],[-1.3,4,0,8.6],[7,0,-8,0.006]]
B = [[3,-5.76,45,0],[2,-2,1.3,9],[-9,0,0,0]]
C = [[0,1009,-66.7849,90],[0,5,4,-0.07],[-7.7,0,0,0]]
i1,j1 = 2,3
i2,j2 = 3,1

sol1 = get_d_ij(A,B,C,i1,j1)
sol2 = get_d_ij(A,B,C,i2,j2)

print("Value of d"+str(i1)+""+str(j1)+": "+str(sol1))
print("Value of d"+str(i2)+""+str(j2)+": "+str(sol2))

Value of d23: -2.7
Value of d31: 5.7


In [5]:
# Just answer using code --> easy stuff!

# Harder
# Can you build a matrix solver that can do output the result given n matrices and a sequence of operations such as [add subtract multiply transpose?]
#Some ideas on valid operations: Multiplication Addition Subtraction Inverstion Transposed.

class NumpyMatrixSolver:
  
    def add(self,A,B):
        return np.array(A) + np.array(B)

    def subtract(self,A,B):
        
        return np.array(A) - np.array(B)
    
    def scalarMultiply(self,a,B):
        return a*np.array(B)
    
    def matrixMultiply(self,A,B):
        return np.matmul(A,B)
    
    def transpose(self,A):
        return np.array(A).T

class MyMatrixSolver:
  
    def add(self,A,B):
        new_B= cp.deepcopy(B)
        for m in range(len(A)):
            for n in range(len(A[m])):
                new_B[m][n] = A[m][n] + B[m][n]
        return new_B

    def subtract(self,A,B):
        new_B= cp.deepcopy(B)
        for m in range(len(A)):
            for n in range(len(A[m])):
                new_B[m][n] = A[m][n] - B[m][n]
        return new_B
    
    def scalarMultiply(self,a,B):
        new_B= cp.deepcopy(B)
        for m in range(len(B)):
            for n in range(len(B[m])):
                new_B[m][n] = a*B[m][n]
        return new_B
    
    def matrixMultiply(self,A,B):
        B_t = self.transpose(B)
        matrix = [[0]*len(B_t) for i in A]
        for m in range(len(A)):
            for n in range(len(B_t)):
                for p in range(len(A[m])):
                    matrix[m][n] += A[m][p]*B_t[n][p]
        return matrix
    
    def transpose(self,B):
        new_B= cp.deepcopy(B)
        for m in range(len(B)):
            for n in range(len(B[m])):
                new_B[m][n] = B[n][m]
        return new_B
 
numpyMatrixSolver = NumpyMatrixSolver()
myMatrixSolver = MyMatrixSolver()

x1 = [[2,3],[1,4]]
x2 = [[1,5],[0,-4]]

print("addition")
print(numpyMatrixSolver.add(x1,x2))
print(myMatrixSolver.add(x1,x2))

print("subtraction")
print(numpyMatrixSolver.subtract(x1,x2))
print(myMatrixSolver.subtract(x1,x2))

print("scalarMultiply")
print(numpyMatrixSolver.scalarMultiply(3,x2))
print(myMatrixSolver.scalarMultiply(3,x2))

print("matrixMultiply")
print(numpyMatrixSolver.matrixMultiply(x1,x2))
print(myMatrixSolver.matrixMultiply(x1,x2))

print("transpose")
print(numpyMatrixSolver.transpose(x1))
print(myMatrixSolver.transpose(x1))


addition
[[3 8]
 [1 0]]
[[3, 8], [1, 0]]
subtraction
[[ 1 -2]
 [ 1  8]]
[[1, -2], [1, 8]]
scalarMultiply
[[  3  15]
 [  0 -12]]
[[3, 15], [0, -12]]
matrixMultiply
[[  2  -2]
 [  1 -11]]
[[2, -2], [1, -11]]
transpose
[[2 1]
 [3 4]]
[[2, 1], [3, 4]]


![title](./img/3_3.png)
Create a program that can output
- How many rows will C have?
- How many columns will C have?
- What will be the value of c13​?

In [6]:
def get_c_r_c_ij(A,B,i,j):
    C = np.array(np.matmul(A,B),ndmin=2)

    return C.shape[0], C.shape[1], C[i-1,j-1]

A = [0.6,-15,2,5,98]
B = [[2,2,-4],[9,-14,0],[13,-0.5,44],[1,9,4],[0,0,5]]
i,j = 1,3

sol = get_c_r_c_ij(A,B,i,j)

print("No of rows of C: ",sol[0])
print("No of columns of C: ",sol[1])
print("Value of C"+str(i)+""+str(j)+": "+str(sol[1]))

No of rows of C:  1
No of columns of C:  3
Value of C13: 3
